import '../styles/style.scss';
import '../public/nprogress.css';
import 'react-loading-skeleton/dist/skeleton.css';

import Head from 'next/head';
import { useRouter } from 'next/router';
import { SessionProvider } from 'next-auth/react';
import NProgress from 'nprogress';
import { useEffect } from 'react';

import FullLayout from '../src/layouts/FullLayout';

function MyApp({ Component, pageProps: { session, ...pageProperties } }) {
  const router = useRouter();

  useEffect(() => {
    const handleStart = url => {
      console.log(`Loading: ${url}`);
      NProgress.start();
    };
    const handleStop = () => {
      NProgress.done();
    };

    router.events.on('routeChangeStart', handleStart);
    router.events.on('routeChangeComplete', handleStop);
    router.events.on('routeChangeError', handleStop);

    return () => {
      router.events.off('routeChangeStart', handleStart);
      router.events.off('routeChangeComplete', handleStop);
      router.events.off('routeChangeError', handleStop);
    };
  }, [router]);

  return (
    <SessionProvider session={session}>
      <Head>
        <title>Exam-cell</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FullLayout>
        <Component {...pageProperties} />
      </FullLayout>
    </SessionProvider>
  );
}

export default MyApp;
